<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Tag;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getPostsByTag(Tag $tag)
    {
        $qb = $this->createQueryBuilder("p")
            ->where(':tag MEMBER OF p.tags')
            ->setParameters(array('tag' => $tag))
        ;
        return $qb->getQuery()->getResult();
    }
}
