<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getTagsByNames(array $tagNames)
    {
        return $this->createQueryBuilder('t')
            ->where('t.name IN(:tagNames)')
            ->setParameter('tagNames', array_values($tagNames))
            ->getQuery()
            ->getResult();
    }
}
